/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e_pehnava;

import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Chaitanya
 */
public class loogin extends javax.swing.JFrame {

    /**
     * Creates new form loogin
     */
    public loogin() {
        
        initComponents();
        {
    }


        }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        t1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(530, 510));
        setSize(new java.awt.Dimension(533, 536));
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Nightclub BTN", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 80, 95));
        jLabel2.setText("Login to E-pehnava");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 50, 150, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(" Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 150, 120, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 240, 90, 20);

        p1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        getContentPane().add(p1);
        p1.setBounds(260, 240, 140, 20);

        t1.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(259, 150, 150, 20);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 53, 95));
        jButton2.setText("SIGNUP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 430, 130, 23);

        jButton1.setForeground(new java.awt.Color(255, 68, 130));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 320, 73, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Not existing customer then Signup here");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 380, 300, 40);

        jButton3.setForeground(new java.awt.Color(255, 51, 204));
        jButton3.setText("Admin Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 450, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chaitanya\\Desktop\\images (12).jpeg")); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(3, 0, 530, 490);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed



      String A=t1.getText();
             int a=Integer.parseInt(A);
             int d=0;
             String C="0",a2="0";
    String b=new String(p1.getPassword());
        try
     {
         Class.forName("java.sql.Driver");
         Connection c=DriverManager.getConnection("jdbc:mysql://localhost/chiku","root","1234");
         Statement s=c.createStatement();
         ResultSet r=s.executeQuery("select phone,password from signup where phone="+a);
         
         while(r.next())
         {
         Object o[]={r.getString(1),r.getString(2)};
                 
          C=o[0].toString().trim();
          a2=o[1].toString().trim();
         }
          d=Integer.parseInt(C);
         
         c.close();
     }
     catch(Exception e)
     {
         e.printStackTrace();
     }
        if(a==d&&b.equals(a2))
    {
        
        JOptionPane.showMessageDialog(null,"Successful Login");
        new home_page().setVisible(true);
        t1.setText(null);
        p1.setText(null);
    }
 
    
        
        else
     {
         JOptionPane.showMessageDialog(null,"Try Again");
         t1.setText(null);
        p1.setText(null);
     }



    }//GEN-LAST:event_jButton1ActionPerformed

  
    
                                           

        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new signup().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new admin_login().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
