/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e_pehnava;

/**
 *
 * @author Chaitanya
 */
import java.sql.*;
import javax.swing.table.*;
import javax.swing.JOptionPane;
public class update1 extends javax.swing.JFrame {

    /**
     * Creates new form update1
     */
    public update1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        l1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        te1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 730));
        setPreferredSize(new java.awt.Dimension(720, 730));
        setSize(new java.awt.Dimension(720, 730));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 11, 0, 0);

        jLabel1.setBackground(new java.awt.Color(255, 51, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Update Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 60, 162, 29);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Enter Phone Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 130, 184, 32);
        getContentPane().add(t1);
        t1.setBounds(280, 140, 182, 20);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Show Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 130, 111, 25);

        t.setBackground(new java.awt.Color(102, 204, 255));
        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Address", "Location", "Phone", "Password"
            }
        ));
        jScrollPane1.setViewportView(t);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 680, 97);

        l1.setBorder(new javax.swing.border.MatteBorder(null));
        l1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        l1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "name", "age", "address", "password" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(l1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(250, 320, 107, 179);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Select the detail to be edited");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 370, 174, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Enter New Value");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 520, 114, 32);

        te1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                te1ActionPerformed(evt);
            }
        });
        getContentPane().add(te1);
        te1.setBounds(210, 530, 170, 20);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 102));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 570, 105, 26);

        t2.setBackground(new java.awt.Color(0, 204, 255));
        t2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Address", "Location", "Phone", "Password"
            }
        ));
        jScrollPane3.setViewportView(t2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 610, 680, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e_pehnava/bg2.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -90, 720, 810);

        jMenu1.setText("Home");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Home");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
{
Class.forName("java.sql.Driver");
Connection c=DriverManager.getConnection("jdbc:mysql://localhost/chiku","root","1234");
Statement s=c.createStatement();
String d=t1.getText();
int e=Integer.parseInt(d);
ResultSet r=s.executeQuery("select * from signup where phone="+e);
DefaultTableModel dt=(DefaultTableModel)t.getModel();
while(r.next())
{
    Object ob[]={r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6)};
    dt.addRow(ob);
}
c.close();
}
catch(Exception e)
{
e.printStackTrace();
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void te1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_te1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_te1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try
        {
        Class.forName("java.sql.Driver");
Connection c=DriverManager.getConnection("jdbc:mysql://localhost/chiku","root","1234");
Statement s=c.createStatement();
int z=Integer.parseInt(t1.getText()); 
String b=te1.getText();
Object f=l1.getSelectedValue();
int d;

if(f.equals("name"))
{
d=s.executeUpdate("update signup set name=' "+b+" ' where phone="+z );
}

if(f.equals("age"))
{
    int c1=Integer.parseInt(b);
d=s.executeUpdate("update signup set age= "+b+"  where phone="+z );
}

if(f.equals("address"))
{
d=s.executeUpdate("update signup set address=' "+b+" ' where phone="+z );
}

if(f.equals("password"))
{
d=s.executeUpdate("update signup set password=' "+b+" ' where phone="+z );
}



ResultSet r=s.executeQuery("select * from signup where phone="+z);
DefaultTableModel dt=(DefaultTableModel)t2.getModel();
while(r.next())
{
    Object ob[]={r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6)};
    dt.addRow(ob);
}

        }
catch(Exception e)
        {
        e.printStackTrace();
        }
JOptionPane.showMessageDialog(null,"Your details have been updated");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
new home_page().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
new home_page().setVisible(true);   
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList l1;
    private javax.swing.JTable t;
    private javax.swing.JTextField t1;
    private javax.swing.JTable t2;
    private javax.swing.JTextField te1;
    // End of variables declaration//GEN-END:variables
}
